apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portfolio-service
  namespace: portfolio-service
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/portfolio-service  # Path to the Helm chart within your Git repository
      sourceRef:
        kind: GitRepository
        name: helm-charts-services
        namespace: flux-system
      interval: 1m0s  # Specify any Helm chart values here
