apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weather-service
  namespace: default
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/weather-service # Path to the Helm chart within your Git repository
      sourceRef:
        kind: GitRepository
        name: helm-charts-services
        namespace: flux-system
      interval: 1m0s # Specify any Helm chart values here.
  values:
    service:
      replicaCount: 1
      image:
        registry: index.docker.io
        tag: 0.0.3 # {"$imagepolicy": "flux-system:weather-service:tag"}
