apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: monitoring
spec:
  interval: 1h0m0s
  releaseName: grafana-k8s-monitoring
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    cluster:
      name: my-cluster
    externalServices:
      prometheus:
        secret:
          create: false
          name: prometheus-secret
          namespace: monitoring     
      loki:
        secret:
          create: false
          name: loki-secret
          namespace: monitoring
      tempo:
        secret:
          create: false
          name: tempo-secret
          namespace: monitoring
    metrics:
      enabled: true
      alloy:
        metricsTuning:
          useIntegrationAllowList: true
      cost:
        enabled: true
      node-exporter:
        enabled: true
    logs:
      enabled: true
      pod_logs:
        enabled: true
      cluster_events:
        enabled: true
    traces:
      enabled: true
    receivers:
      grpc:
        enabled: true
      http:
        enabled: true
      zipkin:
        enabled: true
      grafanaCloudMetrics:
        enabled: false
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-operator-crds:
      enabled: true
    alloy: {}
    alloy-events: {}
    alloy-logs: {}