apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: monitoring
spec:
  interval: 1h0m0s
  releaseName: grafana-k8s-monitoring
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    cluster:
      name: my-cluster
    externalServices:
      prometheus:
        host: https://prometheus-prod-43-prod-ap-south-1.grafana.net
        basicAuth:
          username: "1712723"
          password: "to be added through secret"      
      loki:
        host: https://logs-prod-028.grafana.net
        basicAuth:
          username: "956262"
          password: "to be added through secret"
      tempo:
        host: https://tempo-prod-19-prod-ap-south-1.grafana.net:443
        basicAuth:
          username: "950577"
          password: "to be added through secret"
    metrics:
      enabled: true
      alloy:
        metricsTuning:
          useIntegrationAllowList: true
      cost:
        enabled: true
      node-exporter:
        enabled: true
    logs:
      enabled: true
      pod_logs:
        enabled: true
      cluster_events:
        enabled: true
    traces:
      enabled: true
    receivers:
      grpc:
        enabled: true
      http:
        enabled: true
      zipkin:
        enabled: true
      grafanaCloudMetrics:
        enabled: false
    opencost:
      enabled: true
      opencost:
        exporter:
          defaultClusterId: my-cluster
        prometheus:
          external:
            url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-operator-crds:
      enabled: true
    alloy: {}
    alloy-events: {}
    alloy-logs: {}