apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-stack
  namespace: default
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: grafana-community
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
  # values:
  #   cluster:
  #     name: kind
  #   externalServices:
  #     prometheus:
  #       host: https://prometheus-prod-43-prod-ap-south-1.grafana.net
  #     loki:
  #       host: https://logs-prod-028.grafana.net
  #     tempo:
  #       host: https://tempo-prod-19-prod-ap-south-1.grafana.net:443
  #   metrics:
  #     enabled: true
  #     alloy:
  #       metricsTuning:
  #         useIntegrationAllowList: true
  #     cost:
  #       enabled: true
  #     node-exporter:
  #       enabled: true
  #   logs:
  #     enabled: true
  #     pod_logs:
  #       enabled: true
  #     cluster_events:
  #       enabled: true
  #   traces:
  #     enabled: true
  #   receivers:
  #     grpc:
  #       enabled: true
  #     http:
  #       enabled: true
  #     zipkin:
  #       enabled: true
  #     grafanaCloudMetrics:
  #       enabled: false
  #   opencost:
  #     enabled: true
  #     opencost:
  #       exporter:
  #         defaultClusterId: kind
  #       prometheus:
  #         external:
  #           url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom
  #   kube-state-metrics:
  #     enabled: true
  #   prometheus-node-exporter:
  #     enabled: true
  #   prometheus-operator-crds:
  #     enabled: true
  #   alloy: {}
  #   alloy-events: {}
  #   alloy-logs: {}