---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    server:
      service:
        type: ClusterIP
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: ClusterIP
